{% set name = "urllib3" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df7aa8afb0148fa78488e7899b2c59b5f4ffcfa82e6c54ccb9dd37c1d7b52d54


build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling >=1.6.0,<2
  run:
    - python

test:
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.contrib._securetransport
    - urllib3.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
  description: |
    urllib3 is a powerful, sanity-friendly HTTP client for Python. Much of the
    Python ecosystem already uses urllib3. urllib3 brings many critical features
    that are missing from the Python standard libraries, such as thread safety,
    connection pooling, client side ssl/tls verification, support for gzip and
    deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests
    and dealing with HTTP redirects.
  doc_url: https://urllib3.readthedocs.io/
  dev_url: https://github.com/urllib3/urllib3

extra:
  recipe-maintainers:
    - pmlandwehr
    - sigmavirus24
    - ocefpaf
    - sethmlarson
