travis:
  secure:
    BINSTAR_TOKEN: oqMG9prb2eG1quISQ+zBmDKuo1IDrwA92KOWlbrPjt1QZYSP4fkRWMsWFyvqABVNGfR30rgmga81/hqZedz315dPwUwYoKHTy0resM6H6cZMdeP2u+kVo6YKyKZ7QEy+WocRZGizcYyc9INAsU8nB3eztbn+oXoq2rS5UA9vwtYQ4x8AaQMTYmJe0UUmB77MQzjaibQSB/DyOPu6ySbLnhABYVs/UX9WkgG/Fxmm+KYwMRurhZzj1TGNykH7BFN6EQ605jkq0FaR5++dxdRO4OyDTNqS3LmKMTO03Zri4jStMPHEReZlLD03ATqW/T3hUmSdwXLx/XPVEdYVoEAJ2Yc7VDPRpS3ERauPxf7yxF1G1ZOSDe/BSOPpKEqkWBRg6Yjnn1JEWCriPt7oG4079EfZcKdSM/vS1AmGtRZBKCSGLt4NOk3cttnkMEHxahghiQT6T7hIcfHiJd6wVF4fP4+L7XYTUQO7D1QCjJv99KtocOCA/783uPCOIZ3Eduh4OOqTdSaI4Ot7R6WLTHG0WhjwgbyEtFFBHjfKCcmMEbyMNoW8aLQ4SxSM/c11SDjmQhA+7KjC6FtjhXWdTPvPdAaoS8ZuvSMsDd739hdQs4Rlzt4zt5d1BtDIivtdAhRzwCQ7JcWHodA+y2f7h+Qo1V4cMgjhD0nwGV3EYMkwK9s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
